### ISSUE TITLE
Failed to set up after 2023.12.0

### ISSUE THREAD

**Issue by Bastian007** [myntath/gtasks-ha#11]
After HA update 2023.12.0 a "Failed to set up" error is shown for the custom component gtasks-ha:
![image](https://github.com/myntath/gtasks-ha/assets/12425311/2f37d048-0169-4100-88e0-78b24a780ea1)

The error log shows this message:
User credential refresh is only supported in the default googleapis.com universe domain, but the current universe domain is None. If you created the credential with an access token, it's likely that the provided token is expired now, please update your code with a valid token.

## Version of the custom_component
v0.6.1

## Error log

`This error originated from a custom integration.

Logger: custom_components.gtasks
Source: custom_components/gtasks/__init__.py:135
Integration: GTasks (documentation)
First occurred: 08:50:18 (1 occurrences)
Last logged: 08:50:18

User credential refresh is only supported in the default googleapis.com universe domain, but the current universe domain is None. If you created the credential with an access token, it's likely that the provided token is expired now, please update your code with a valid token.
Traceback (most recent call last):
  File "/config/custom_components/gtasks/__init__.py", line 135, in async_setup_entry
    gapi = await hass.async_add_executor_job(GtasksAPI, creds, token_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtasks/gtasks_api.py", line 25, in __init__
    self._connect()
  File "/config/custom_components/gtasks/gtasks_api.py", line 41, in _connect
    self._creds.refresh(Request())
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/credentials.py", line 338, in refresh
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: User credential refresh is only supported in the default googleapis.com universe domain, but the current universe domain is None. If you created the credential with an access token, it's likely that the provided token is expired now, please update your code with a valid token.
`

**Comment by myntath** [comment]
I am not experiencing this issue and can confirm I'm on 2023.12.0, however, this is just on a straight upgrade on an existing working install. I haven't tried setting up the component fresh.

I can't find a lot of information on universe domains.

What have you tried so far to fix? Have you deleted credentials and setup again?

**Comment by Bastian007** [comment]
I was not able to re-setup the component with the same pathes as in the past: ./custom_components/gtasks/
where also the credential was sitting.
Is your credential placed in that folder?

However, when I place the credential.json to the root of config folder and place also the config folder as writeable path it is possible to setup successfully.

So my assumption would be that they have changed some folder right with 2023.12.
I stumbled over that dev blog entry, not sure if it is somehow related: https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/
